# Generated by Django 5.2.2 on 2025-06-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tname", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("qualification", models.CharField(blank=True, max_length=100)),
                ("contact", models.CharField(blank=True, max_length=100)),
                ("leave_record", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
