# Generated by Django 5.2.2 on 2025-06-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name="users",
            table="userss",
        ),
    ]
